const kurlyDB = [
    {
        src:'./images/kurly_001.jpg',
        name:'[해태] 여름 시즌 한정 트로피컬 에디션 간식 4종 (택1)',
        summary:'새콤달콤한 여름맛 간식',
        price:3580,
        sale:7,
        review:154,
    },
    {
        src:'./images/kurly_002.jpg',
        name:'[피자로빈슨] 뉴욕 메가 슬라이스 피자 페퍼로니',
        summary:'짭쪼름한 페퍼로니가 듬뿍',
        price:5500,
        sale:20,
        review:18,
    },{
        src: './images/kurly_003.jpg',
        name: '[오뚜기] 진라면 매운맛 5입',
        summary: '매콤한 국물의 정석',
        price:3980,
        sale:15,
        review:312,
    },
    {
        src: './images/kurly_004.jpg',
        name: '[빙그레] 바나나맛 우유 4입',
        summary: '부드러운 달콤함',
        price:2980,
        sale:10,
        review:201,
    },
    {
        src: './images/kurly_005.jpg',
        name: '[CJ] 비비고 왕교자 1.05kg',
        summary: '속이 꽉 찬 만두의 맛',
        price:9480,
        sale:25,
        review:987,
    },
    {
        src: './images/kurly_006.jpg',
        name: '[풀무원] 얇은피꽉찬속 김치만두',
        summary: '얇은 피로 꽉 채운 김치의 맛',
        price:5980,
        sale:18,
        review:432,
    },
    {
        src: './images/kurly_007.jpg',
        name: '[매일] 바리스타룰스 아메리카노 330ml',
        summary: '진한 에스프레소의 풍미',
        price:2200,
        sale:5,
        review:86,
    },
    {
        src: './images/kurly_008.jpg',
        name: '[샘표] 연두 순 식물성 조미료 275g',
        summary: '요리의 감칠맛을 책임져요',
        price:3980,
        sale:12,
        review:158,
    },
    {
        src: './images/kurly_009.jpg',
        name: '[남양] 맛있는 우유 GT 1L',
        summary: '신선함 그대로 담은 우유',
        price:2480,
        sale:8,
        review:94,
    },
    {
        src: './images/kurly_010.jpg',
        name: '[노브랜드] 감자칩 오리지널 110g',
        summary: '바삭한 식감의 대표 간식',
        price:1580,
        sale:10,
        review:312,
    },
    {
        src: './images/kurly_011.jpg',
        name: '[동원] 양반 김 도시락김 16봉',
        summary: '짭조름하고 고소한 김',
        price:5980,
        sale:20,
        review:276,
    },
    {
        src: './images/kurly_012.jpg',
        name: '[삼양] 불닭볶음면 5입',
        summary: '화끈한 매운맛의 인기 라면',
        price:4480,
        sale:30,
        review:651,
    }
]